spring:
  application:
    name: spring-cloud-eureka-server
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    enableSelfPreservation: false
server:
  port: 8761