spring:
  application:
    name: spring-cloud-gateway
  profiles:
    active: dev
  config:
    import: optional:configserver:http://config-server:8080
---
spring:
  application:
    name: spring-cloud-gateway
  profiles:
    active: stg
  config:
    import: optional:configserver:http://config-server:8080
---
spring:
  application:
    name: spring-cloud-gateway
  profiles:
    active: prod
  config:
    import: optional:configserver:http://config-server:8080