spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/damvuong/spring-cloud
          searchPaths: configuration